-   id: js-beautify
    name: js-beautify
    entry: js-beautify
    language: node
    files: \.js$
    args: []

    # Use additional_dependencies to install the actual node package
    additional_dependencies: ['js-beautify@1.13.0']
    minimum_pre_commit_version: 1.0.0
